name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '3,13,23,33,43,53 * * * *'  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://comparison-of-knn-and-svm.onrender.com > /dev/null